---

- name: set mysql root password
  mysql_user: name={{ mysql_root }} host={{ mysql_host }} password={{ mysql_root_password }}
  when: mysql.changed

- name: create project databases
  mysql_db: name={{ item.database }} login_user={{ mysql_root }} login_password={{ mysql_root_password }} login_host={{ mysql_host }} state=present
  with_items: "{{ mysql_user_configuration }}"

- name: create project database user
  mysql_user: name={{ item.user }} password={{ item.password }} priv={{ item.database }}.*:ALL state=present login_user=root login_password={{ mysql_root_password }} append_privs=yes
  with_items: "{{ mysql_user_configuration }}"

- name: restart mysql service
  service: name={{ mysql_service }} state=restarted
