---

- name: include vars
  include_vars: ../vars/{{ ansible_os_family }}_vars.yml

- include: "install-{{ ansible_os_family }}.yml"
  static: no

- include: "configure-{{ ansible_os_family }}.yml"
  static: no
